name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
    tags-ignore:
      - "**.*"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Step 3: Clear npm cache
      - name: Clear NPM Cache
        run: npm cache clean --force

      # Step 4: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.0'

      # Step 5: Install dependencies
      - name: Install NPM dependencies
        run: npm install

      # Step 6: Build Angular app
      - name: Build Angular App
        run: npm run build --output-path=dist/tour-of-heroes/browser --base-href=/

      # Step 7: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 8: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          # Build the image and tag it with the commit SHA
          docker build -t halludbam/angular-heroes-app:${{ github.sha }} .
          
          # Also tag it as 'latest'
          docker tag halludbam/angular-heroes-app:${{ github.sha }} halludbam/angular-heroes-app:latest
          
          # Log in to Docker Hub
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
          # Push both tags
          docker push halludbam/angular-heroes-app:${{ github.sha }}
          docker push halludbam/angular-heroes-app:latest

      # Step 9: Install Terraform
      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install -y terraform

      # Step 10: Deploy with Terraform
      - name: Deploy with Terraform
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          terraform init
          terraform apply -auto-approve \
            -var "EC2_PRIVATE_KEY=${EC2_PRIVATE_KEY}" \
            -var "commit_sha=${{ github.sha }}"

      # Step 11: Restart Nginx with New Configurations
      - name: Restart Nginx
        run: |
          CONTAINER_ID=$(docker ps -qf "name=angular-heroes-app")
          docker exec -it $CONTAINER_ID nginx -s reload
