name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
    tags-ignore:
      - "**.*"
  workflow_dispatch:  # Allows manual triggering of the pipeline

jobs:
  build-and-deploy:
    # Only run if 'ci-cd' is in the commit message
    if: contains(github.event.head_commit.message, 'ci-cd')
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Clear the npm cache (no working-directory needed if package.json is in root)
      - name: Clear npm cache
        run: npm cache clean --force

      # Step 3: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.0'

      # Step 4: Install npm dependencies
      - name: Install Dependencies
        run: npm install

      # Step 5: Build the Angular App
      - name: Build Angular App
        run: npm run build

      # Step 6: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 7: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          # Build an image tagged with the commit SHA
          docker build -t halludbam/angular-heroes-app:${{ github.sha }} .
          
          # Optionally also tag 'latest' so your EC2 instance can pull it
          docker tag halludbam/angular-heroes-app:${{ github.sha }} halludbam/angular-heroes-app:latest
          
          # Log into Docker Hub
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
          # Push both tags
          docker push halludbam/angular-heroes-app:${{ github.sha }}
          docker push halludbam/angular-heroes-app:latest

      # Step 8: Install Terraform
      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install -y terraform

      # Step 9: Deploy with Terraform
      - name: Deploy with Terraform
        run: |
          terraform init
          terraform apply -auto-approve
